---
title: "etosha_ssf"
output: html_document
---


Following the [tutorial](https://cran.r-project.org/web/packages/amt/vignettes/p4_SSF.html) by Johannes Signer.

```{r}
#| include: false
# general use
library(tidyverse)
library(janitor)
library(here)
library(tools)

# spatial
library(terra)
library(amt) # ssf
```

```{r}
#| include: false
# ----- loading new data -----
etosha_folder <- here("data", "Elephant movements", "Etosha")
kunene_folder <- here("data", "Elephant movements", "Kunene")
omusati_folder <- here("data", "Elephant movements", "Omusati")

ele_data1 <- NULL
for (folder in c(etosha_folder, kunene_folder, omusati_folder)){
  for (file in list.files(folder)) {
    file_path <- paste0(folder,"/", file)
    collar_table <- read_csv(file_path) |> clean_names()
    
    if (folder == etosha_folder) {
      collar_table <- collar_table |> mutate(region = "etosha")
    } else {
      if (folder == kunene_folder) {
        collar_table <- collar_table |>  mutate(region = "kunene")
      } else {
          collar_table <- collar_table |> mutate(region = "omusati")
        }
      }
    ele_data1 <- bind_rows(ele_data1, collar_table)
  }
}
```


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Step 1: Getting the data ready
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```{r}
ele_clean1 <- ele_data1 |> 
  clean_names() |> 
  rename(dt = timestamp,
         lon = location_long,
         lat = location_lat,
         id = tag_local_identifier) |> 
  mutate(season = case_when(
    month(dt) %in% c(5:10) ~ "dry",
    month(dt) %in% c(1:4, 11:12) ~ "wet"
  ))

```

```{r}
# separating by population
ele_etosha <- ele_clean1 |> 
  filter(region == "etosha")

ele_west <- ele_clean1 |> 
  filter(region %in% c("kunene", "omusati"))

# structure tracking data
ele_trk_etosha <- make_track(ele_etosha,
                      .x = lon, .y = lat, .t = dt,
                      id = id, crs = 4326)

ele_trk_west <- make_track(ele_west,
                      .x = lon, .y = lat, .t = dt,
                      id = id, crs = 4326)
```

```{r}
summarize_sampling_rate(ele_trk_etosha, time_unit = "sec") # sampling rate should be ?
summarize_sampling_rate(ele_trk_west, time_unit = "sec")
```

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Step 2: Prepare data for SSF
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
#| include: false
resample_trk <- function(trk) {
  trk |> 
  # nest all data except for id
  nest(data = -id) |> 
  # for every xyt in data, resample and create steps by burst, and store in 'steps' column
  mutate(steps = map(data, function(x) {
    x |>
      track_resample(rate = hours(6), tolerance = minutes(15)) |>
      steps_by_burst()
  })) |>
  # select id and steps column
  select(id, steps) |> 
  # unnest everything in steps column
  unnest(cols = steps)
}

random_steps_by_id <- function(reg_trk) {
  reg_trk |>
    nest(data = -id) |>
    mutate(data = map(data, ~ random_steps(.x, n = 10))) |>
    mutate(data = map2(data, id, ~ mutate(.x, id = .y))) |>  # <- reattach id inside, keeps class
    pull(data) |>
    bind_rows()
}

# Set seed before generating any random steps
set.seed(123)
# Resample based on elephant ID 
ele_etosha_reg <- resample_trk(ele_trk_etosha) |> filter(!is.na(sl_), sl_ > 0) |>  random_steps_by_id()
#ele_west_reg <- resample_trk(ele_trk_west) |> random_steps_by_id()

#ele_dry_reg <- resample_trk(ele_trk_dry)
#ele_wet_reg <- resample_trk(ele_trk_wet)

# create random/control steps
#set.seed(123)
#ele_dry_reg <- ele_dry_reg |> random_steps(10)
#ele_wet_reg <- ele_wet_reg |> random_steps(10)
```

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Step 3: Prepare raster stack for static covariates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
file_paths <- c()

gee_folder <- here("data", "500m_data")

# create a vector of file paths to each raster
# EVI and world population added manually later for each corresponding season/year

for (file in list.files(gee_folder)[list.files(gee_folder) %in% c("core_dist_rast_500m.tif", "fences_dist_rast_500m.tif", "roads_distance_rast_500m.tif", "terrain_rast_500m.tif")]) {
  file_paths <- c(file_paths, paste0(gee_folder,"/", file))
}
# set up for raster stack
crop_extent <- ext(12.5, 25.5, -21.5, -16.5)
target_res <- 0.0045 # 500m resolution

template <- rast(crop_extent, resolution = target_res, crs = "EPSG:4326")

raster_list <- c()

# create raster stack
raster_list <- map(file_paths, function(fp) {
  r <- rast(fp)                                                                 # turn file path into raster
  project(r, template, method = "bilinear")                                     # project
})

raster_stack <- rast(raster_list)                                               # create stack from list

# which(names(raster_stack) == "distance")
names(raster_stack)[c(1:3)] <- c("core_dist", "fence_dist", "road_dist")
```


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Step 4: Extracting covariates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
# Static layer extraction 

gee_folder <- here("data", "500m_data")

extract_static <- function(ele_trk){
  file_paths <- c()

  for (file in list.files(gee_folder)[list.files(gee_folder) %in% c("core_dist_rast_500m.tif", "fences_dist_rast_500m.tif", "roads_distance_rast_500m.tif")]) {
    file_paths <- c(file_paths, paste0(gee_folder,"/", file))
  }
  # set up for raster stack
  crop_extent <- ext(12.5, 25.5, -21.5, -16.5)
  target_res <- 0.0045 # 500m resolution
  template <- rast(crop_extent, resolution = target_res, crs = "EPSG:4326")
  r_list <- c()
  # create raster stack
  r_list <- map(file_paths, function(fp) {
    r <- rast(fp)                                                                 # turn file path into raster
    project(r, template, method = "bilinear")                                     # project
  })
  r_stack <- rast(r_list)                                               # create stack from list
  # which(names(r_stack) == "distance")
  names(r_stack)[c(1:3)] <- c("core_dist", "fence_dist", "road_dist")  
  
  r_terrain <- rast(paste0(gee_folder, "/terrain_rast_500m.tif"))
  
  static_extract <- ele_trk 
  static_extract <- static_extract |> 
    extract_covariates(r_stack) |> 
    mutate(terrain_list = extract_covariates_along(static_extract, covariates = r_terrain)) |> 
    mutate(terrain_means = map(terrain_list, function(df){
        as.data.frame(t(colMeans(df, na.rm = TRUE)))
      })) |> 
    # mutate(static_list = extract_covariates_along(static_extract, covariates = r_stack)) |> 
    # mutate(
    #   static_means = map(static_list, function(df){
    #     as.data.frame(t(colMeans(df, na.rm = TRUE)))
    #   })) |>
    unnest(cols = terrain_means)
  
  class(static_extract) <- class(ele_trk)
  return(static_extract)
}
```


```{r}
# EVI extraction loop

evi_folder <- here("data", "500m_data", "EVI data")
wet_months <- c(1:4, 11:12)
dry_months <- c(5:10)

extract_evi <- function(ele_trk) {
  
  if("EVI" %in% colnames(ele_trk) | "evi" %in% colnames(ele_trk)){
    return(ele_trk)
  }
  ele_trk_mutated <- ele_trk
  # create yearly and seasonal data if needed  
  if(!"year" %in% colnames(ele_trk)){
    ele_trk_mutated <- ele_trk_mutated |>
      mutate(year = year(t2_))
  }
  if(!"season" %in% colnames(ele_trk)){
    ele_trk_mutated <- ele_trk_mutated |> 
      mutate(season = case_when(
           month(t2_) %in% wet_months ~ "wet",
           month(t2_) %in% dry_months ~ "dry"))
  }
  # initialize output
  new_trk <- tibble()
  for (yr in 2008:2020) {
    for (szn in c("dry", "wet")) {
      # for each iteration, filter for a year and season
      evi_extract <- ele_trk_mutated |> 
        filter(year == yr,
               season == szn)
      # if no rows exist, move on
      if (nrow(evi_extract) == 0){next}
      # if season is dry, use the dry season evi
      if (szn == "dry"){
        r <- rast(paste0(evi_folder, "/", "evi_dry_", yr, ".tif"))
        names(r) <- "evi"
        evi_extract <- evi_extract |> 
          extract_covariates(r)
          # mutate(evi_list = extract_covariates_along(evi_extract, covariates = r)) |> 
          # mutate(evi = map(evi_list, ~ mean(.x, na.rm = TRUE)))
      # if season is wet, use evi rasters from tail ends of the year
      } else{
        r1 <- rast(paste0(evi_folder, "/", "evi_wet_", yr - 1,"_", yr, ".tif"))
        r2 <- rast(paste0(evi_folder, "/", "evi_wet_", yr,"_", yr + 1, ".tif"))
        names(r1) <- "evi"
        names(r2) <- "evi"
        sub1 <- evi_extract |> 
          filter(month(t2_) %in% 1:4) 
        if (nrow(sub1) > 0) {
          sub1 <- sub1 |> 
            extract_covariates(r1)}
            # mutate(evi_list = extract_covariates_along(sub1, covariates = r1)) |> 
            # mutate(evi = map(evi_list, ~ mean(.x, na.rm = TRUE)))}
        sub2 <- evi_extract |> 
          filter(month(t2_) %in% 11:12) 
        if (nrow(sub2) > 0) {
          sub2 <- sub2 |> 
            extract_covariates(r2)}
            # mutate(evi_list = extract_covariates_along(sub2, covariates = r2)) |> 
            # mutate(evi = map(evi_list, ~ mean(.x, na.rm = TRUE)))}
        evi_extract <- bind_rows(sub1, sub2)
      }
      # bind newly extracted rows to new dataframe
      new_trk <- bind_rows(new_trk, evi_extract)
    }
  }
  # new_trk <- new_trk |> 
  #   unnest(cols = evi)
  
  class(new_trk) <- class(ele_trk)
  return(new_trk)
}

# extract evi to base extractions
# ele_trk_extract_etosha <- extract_evi(ele_trk_extract_etosha)
#ele_trk_extract_west <- extract_evi(ele_trk_extract_west)
```

```{r}
# World population extraction loop

world_pop <- rast(here("data", "500m_data", "worldPop_comb_img_500m.tif"))
world_pop_list <- split(world_pop, 1:nlyr(world_pop))

extract_world_pop <- function(ele_trk){
  ele_trk_mutated <- ele_trk
  if(!"year" %in% colnames(ele_trk)){
    ele_trk_mutated <- ele_trk_mutated |>
      mutate(year = year(t2_))}  
  # initialize output
  new_trk <- tibble()
  for(yr in 2008:2020){
    pop_extract <- ele_trk_mutated |> 
      filter(year == yr)
    if(nrow(pop_extract) == 0){next}
    list_pos <- yr - 1999
    r <- world_pop_list[[list_pos]]
    names(r) <- "world_pop"
    
    class(pop_extract) <- class(ele_trk)  # restore track_xyt class
    pop_extract <- pop_extract |> 
      extract_covariates(r)
          # mutate(pop_list = extract_covariates_along(pop_extract, covariates = r)) |> 
          # mutate(world_pop = map(pop_list, ~ mean(.x, na.rm = TRUE)))
    new_trk <- bind_rows(new_trk, pop_extract)
  }
  # new_trk <- new_trk |> 
  #   unnest(cols = world_pop)
  
  class(new_trk) <- class(ele_trk)
  return(new_trk)
}

# ele_trk_extract_etosha <- extract_world_pop(ele_trk_extract_etosha)
# ele_trk_extract_west <- extract_world_pop(ele_trk_extract_west)
```

```{r}
# Land cover dist extraction

lc_types <- c("cropland", "grassland", "shrubland", "tree_cover", "urban", "water_rivers")
lc_dist_folder <- here("data", "ESACCI_LCCS", "lc_dist_2")

extract_lc_dist <- function(ele_trk){
  ele_trk_mutated <- ele_trk
  if(!"year" %in% colnames(ele_trk)){
    ele_trk_mutated <- ele_trk_mutated |>
      mutate(year = year(t2_))}    

  new_trk <- tibble()
  
  for(yr in 2008:2020){
    lc_extract <- ele_trk_mutated |> 
      filter(year == yr)
    if(nrow(lc_extract) == 0){next}
    
    r_list <- list()
    for(i in 1:length(lc_types)){
      lc <- lc_types[i]
      r <- rast(paste0(lc_dist_folder, "/", "dist_", lc, "_", yr, ".tif"))
      names(r) <- paste0(lc, "_dist")
      r_list[[i]] <- r
    }
    r_stack <- rast(r_list)
    
    lc_extract <- lc_extract |> 
      extract_covariates(r_stack)
    #   mutate(lc_dist_list = extract_covariates_along(lc_extract, r_stack)) |> 
    #   mutate(lc_dist_means = map(lc_dist_list, function(df){
    #   if(nrow(df) > 1){as.data.frame(t(colMeans(df, na.rm = TRUE)))
    #     } else{as.data.frame(df)}
    # }))
    
    new_trk <- bind_rows(new_trk, lc_extract)
  }
  # new_trk <- new_trk |> 
  #   unnest(cols = lc_dist_means)
  
  class(new_trk) <- class(ele_trk)
  return(new_trk)
}
```

```{r}
# Linear feature extraction


linear_folder <- here("data", "Linear_features")
linear_types <- c("hydrorivers")

extract_linear <- function(ele_trk){
  new_trk <- ele_trk
  
  r_list <- list()
  
# --- temporary
  crop_extent <- ext(12.5, 25.5, -21.5, -16.5)
  target_res <- 0.0045 # 500m resolution
  template <- rast(crop_extent, resolution = target_res, crs = "EPSG:4326")  
# --- end
  
  for(i in 1:length(linear_types)){
    feature <- linear_types[i]
    r <- rast(paste0(linear_folder, "/", feature, "_Raster_corrected.tif"))
    r <- project(r, template, method = "bilinear")
    names(r) <- paste0(feature, "_linear")
    r_list[[i]] <- r
  }

# --- temporary
  r_list[[2]] <- project(rast(paste0(here("data", "500m_data", "core_dist_rast_500m.tif"))), template, method = "bilinear")
  r_stack <- rast(r_list)
# --- end
  
  new_trk <- new_trk |> 
    mutate(linear_list = extract_covariates_along(new_trk, r_stack)) |> 
    mutate(linear_max = map(linear_list, function(df){
      if(nrow(df) > 1){
        as.data.frame(t(sapply(df, max, na.rm = TRUE)))
        } else{as.data.frame(df)}
    })) |> 
    unnest(cols = linear_max)
  
  class(new_trk) <- class(ele_trk)
  return(new_trk)
}

```


```{r}
#test code
test_slice <- head(ele_etosha_reg, n = 10000) |> 
  extract_evi() |> 
  extract_world_pop() |> 
  extract_static() |> 
  extract_lc_dist() |> 
  extract_linear()
  
# this works!
```

```{r}
ele_trk_extract_etosha <- ele_etosha_reg |> 
  extract_evi() |> 
  extract_world_pop() |> 
  extract_static() |> 
  extract_lc_dist() |> 
  extract_linear()
```


```{r}
# clean names and add columns for log step length and cos turning angle

# ele_trk_extract_etosha <- ele_trk_extract_etosha |> 
#   clean_names() |> 
#   mutate(
#     log_sl = log(sl),
#     cos_ta = cos(ta)
#   )
# ele_trk_extract_west <- ele_trk_extract_west |> 
#   clean_names() |> 
#   mutate(
#     log_sl = log(sl),
#     cos_ta = cos(ta)
#   )

# update to make step_id unique to each elephant before fitting
ele_trk_extract_etosha <- ele_trk_extract_etosha |>
  mutate(step_id = paste(id, step_id, sep = "_"))

ele_trk_extract_west <- ele_trk_extract_west |>
  mutate(step_id = paste(id, step_id, sep = "_"))

# Log-transform population density: raw variable data is heavily right-skewed
# (99th pctile 0.27, max 9.5, driven by <20 near-settlement pixels).
# ele_trk_extract_dry <- ele_trk_extract_dry |>
#   mutate(log_pop_density_2020 = log1p(pop_density_2020))
# 
# ele_trk_extract_wet <- ele_trk_extract_wet |>
#   mutate(log_pop_density_2020 = log1p(pop_density_2020))

```


```{r}
# Splitting by season

ele_trk_extract_etosha_wet <- ele_trk_extract_etosha |> 
  filter(season == "wet")
ele_trk_extract_etosha_dry <- ele_trk_extract_etosha |>  
  filter(season == "dry")

ele_trk_extract_west_wet <- ele_trk_extract_west |> 
  filter(season == "wet")
ele_trk_extract_west_dry <- ele_trk_extract_west |> 
  filter(season == "dry")
```


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Step 5: Fitting the SSF
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
# etosha model
m0_etosha_wet <- ele_trk_extract_etosha_wet |> fit_clogit(case ~ 
                                            core_dist + water_dist + forest_dist + crop_dist + 
                                            built_dist + fence_dist + river_dist + road_dist + 
                                            elevation + slope + aspect + 
                                            evi + world_pop + strata(step_id),
                                          model = FALSE)
summary(m0_etosha_wet)

m0_etosha_dry <- ele_trk_extract_etosha_dry |> fit_clogit(case ~ 
                                            core_dist + water_dist + forest_dist + crop_dist + 
                                            built_dist + fence_dist + river_dist + road_dist + 
                                            elevation + slope + aspect + 
                                            evi + world_pop + strata(step_id),
                                          model = FALSE)

summary(m0_etosha_dry)

# western populations model
m0_west_wet <- ele_trk_extract_west_wet |> fit_clogit(case ~ 
                                            core_dist + water_dist + forest_dist + crop_dist + 
                                            built_dist + fence_dist + river_dist + road_dist + 
                                            elevation + slope + aspect + 
                                            evi + world_pop + strata(step_id),
                                          model = FALSE)
summary(m0_west_wet)

m0_west_dry <- ele_trk_extract_west_dry |> fit_clogit(case ~ 
                                            core_dist + water_dist + forest_dist + crop_dist + 
                                            built_dist + fence_dist + river_dist + road_dist + 
                                            elevation + slope + aspect + 
                                            evi + world_pop + strata(step_id),
                                          model = FALSE)
summary(m0_west_dry)

```

```{r}
#save model outputs
saveRDS(m0_wet, here("outputs/m0_wet.rds"))
saveRDS(m0_dry, here("outputs/m0_dry.rds"))
saveRDS(ele_trk_extract_wet, here("outputs/ele_trk_extract_wet.rds"))
saveRDS(ele_trk_extract_dry, here("outputs/ele_trk_extract_dry.rds"))
# save raster stacks
saveRDS(raster_stack_wet, here("outputs/raster_stack_wet.rds"))
saveRDS(raster_stack_dry, here("outputs/raster_stack_dry.rds"))
```

