---
title: "Step selection function"
author: "Henderson Vo, Marissa Brenner, Rachel Frost"
date: "2026-07-31"
output: html_document
---

Following the [tutorial](https://cran.r-project.org/web/packages/amt/vignettes/p4_SSF.html) by Johannes Signer.

```{r}
#| include: false
# general use
library(tidyverse)
library(janitor)
library(here)
library(tools)

# spatial
library(terra)
library(amt) # ssf
```

```{r}
# ----- loading data -----
ele_data0 <- read_csv(here("data", "elephant_2010-Feb2020.csv"))
```

```{r}
#| include: false
# ----- loading new data -----
etosha_folder <- here("data", "Elephant movements", "Etosha")
kunene_folder <- here("data", "Elephant movements", "Kunene")
omusati_folder <- here("data", "Elephant movements", "Omusati")

ele_data1 <- NULL
for (folder in c(etosha_folder, kunene_folder, omusati_folder)){
  for (file in list.files(folder)) {
    file_path <- paste0(folder,"/", file)
    collar_table <- read_csv(file_path) |> clean_names()
    
    if (folder == etosha_folder) {
      collar_table <- collar_table |> mutate(region = "etosha")
    } else {
      if (folder == kunene_folder) {
        collar_table <- collar_table |>  mutate(region = "kunene")
      } else {
          collar_table <- collar_table |> mutate(region = "omusati")
        }
      }
    ele_data1 <- bind_rows(ele_data1, collar_table)
  }
}
```


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Step 1: Getting the data ready
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```{r}
# cleaning data
ele_clean0 <- ele_data0 |> 
  clean_names() |> 
  mutate(dt = mdy_hm(dt)) |> 
  mutate(season = case_when(
    month %in% c(5:10) ~ "dry",
    month %in% c(1:4, 11:12) ~ "wet"
  ))

ele_clean1 <- ele_data1 |> 
  clean_names() |> 
  rename(dt = timestamp,
         lon = location_long,
         lat = location_lat,
         id = tag_local_identifier) |> 
  mutate(season = case_when(
    month(dt) %in% c(5:10) ~ "dry",
    month(dt) %in% c(1:4, 11:12) ~ "wet"
  ))

ele_join <- bind_rows(ele_clean0, ele_clean1)
```

```{r}
# separating by season
ele_dry <- ele_join |> 
  filter(season == "dry")

ele_wet <- ele_join |> 
  filter(season == "wet")

# structure tracking data
ele_trk_dry <- make_track(ele_dry,
                      .x = lon, .y = lat, .t = dt,
                      id = id, crs = 4326)

ele_trk_wet <- make_track(ele_wet,
                      .x = lon, .y = lat, .t = dt,
                      id = id, crs = 4326)
```

```{r}
summarize_sampling_rate(ele_trk_dry, time_unit = "sec") # sampling rate should be ?
summarize_sampling_rate(ele_trk_wet, time_unit = "sec")
```

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Step 2: Prepare data for SSF
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
#| include: false
resample_trk <- function(trk) {
  trk |> 
  # nest all data except for id
  nest(data = -id) |> 
  # for every xyt in data, resample and create steps by burst, and store in 'steps' column
  mutate(steps = map(data, function(x) {
    x |>
      track_resample(rate = hours(4), tolerance = minutes(15)) |>
      steps_by_burst()
  })) |>
  # select id and steps column
  select(id, steps) |> 
  # unnest everything in steps column
  unnest(cols = steps)
}

random_steps_by_id <- function(reg_trk) {
  reg_trk |>
    nest(data = -id) |>
    mutate(data = map(data, ~ random_steps(.x, n = 10))) |>
    mutate(data = map2(data, id, ~ mutate(.x, id = .y))) |>  # <- reattach id inside, keeps class
    pull(data) |>
    bind_rows()
}

# Set seed before generating any random steps
set.seed(123)
# Resample based on elephant ID 
ele_dry_reg <- resample_trk(ele_trk_dry) |> random_steps_by_id()
ele_wet_reg <- resample_trk(ele_trk_wet) |> random_steps_by_id()

#ele_dry_reg <- resample_trk(ele_trk_dry)
#ele_wet_reg <- resample_trk(ele_trk_wet)

# create random/control steps
#set.seed(123)
#ele_dry_reg <- ele_dry_reg |> random_steps(10)
#ele_wet_reg <- ele_wet_reg |> random_steps(10)
```

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Step 3: Prepare raster stack for environmental covariates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
file_paths_wet <- c()
file_paths_dry <- c()

wet_folder <- here("data", "baseline_2020_with_spei", "wet_szn")
dry_folder <- here("data", "baseline_2020_with_spei", "dry_szn")

# create a vector of file paths to each raster

for (file in list.files(wet_folder)) {
  file_paths_wet <- c(file_paths_wet, paste0(wet_folder,"/", file))
}
for (file in list.files(dry_folder)) {
  file_paths_dry <- c(file_paths_dry, paste0(dry_folder,"/", file))
}
```

```{r}
# set up for raster stack

crop_extent <- ext(18.461667,  25.283338, -20.916664, -17.133330)
test_crop <- ext(12.5, 25.5, -21.5, -16.5)
target_res <- 0.0045 # 500m resolution

template <- rast(test_crop, resolution = target_res, crs = "EPSG:4326")

raster_list_wet <- c()
raster_list_dry <- c()

# create raster stack
raster_list_wet <- map(file_paths_wet, function(fp) {
  r <- rast(fp)                                                                 # turn file path into raster
  r <- r[[nlyr(r)]]                                                             # only include the last layer
  project(r, template, method = "bilinear")                                     # project
})

raster_list_dry <- map(file_paths_dry, function(fp) {
  r <- rast(fp)                                                                 # turn file path into raster
  r <- r[[nlyr(r)]]                                                             # only include the last layer
  project(r, template, method = "bilinear")                                     # project
})

raster_stack_wet <- rast(raster_list_wet)                                       # create stack from list
raster_stack_dry <- rast(raster_list_dry)

names(raster_stack_wet) <- file_path_sans_ext(basename(file_paths_wet))         # rename rasters to file name
names(raster_stack_wet) <- substring(names(raster_stack_wet), 4)                # remove numerical prefix
names(raster_stack_dry) <- file_path_sans_ext(basename(file_paths_dry))
names(raster_stack_dry) <- substring(names(raster_stack_dry), 4)

```


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Step 4: Fitting SSF
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
# Preliminary step: extract covariates to points
ele_trk_extract_dry <- ele_dry_reg |> 
  extract_covariates(raster_stack_dry)

ele_trk_extract_wet <- ele_wet_reg |> 
  extract_covariates(raster_stack_wet)
```

```{r}
# clean names and add columns for log step length and cos turning angle

ele_trk_extract_dry <- ele_trk_extract_dry |> clean_names() |> 
  mutate(
    log_sl = log(sl),
    cos_ta = cos(ta)
  )
ele_trk_extract_wet <- ele_trk_extract_wet |> clean_names() |> 
  mutate(
    log_sl = log(sl),
    cos_ta = cos(ta)
  )

# update to make step_id unique to each elephant before fitting
ele_trk_extract_dry <- ele_trk_extract_dry |>
  mutate(step_id = paste(id, step_id, sep = "_"))

ele_trk_extract_wet <- ele_trk_extract_wet |>
  mutate(step_id = paste(id, step_id, sep = "_"))

# Log-transform population density: raw variable data is heavily right-skewed
# (99th pctile 0.27, max 9.5, driven by <20 near-settlement pixels).
ele_trk_extract_dry <- ele_trk_extract_dry |>
  mutate(log_pop_density_2020 = log1p(pop_density_2020))

ele_trk_extract_wet <- ele_trk_extract_wet |>
  mutate(log_pop_density_2020 = log1p(pop_density_2020))

```

```{r}
# dry season model
m0_dry <- ele_trk_extract_dry |> fit_issf(case ~ sl + log_sl + cos_ta + 
                                            built_2020 + cropland_2020 + grassland_2020 + shrub_2020 + 
                                            tree_2020 + water_2020 + core_dist_rast + rivers_dist_rast + 
                                            roads_distance_rast + fences_dist_rast + log_pop_density_2020 + 
                                            dry_szn_evi_2020 + elevation + slope + aspect + strata(step_id),
                                          model = FALSE)
summary(m0_dry)

# wet season model
m0_wet <- ele_trk_extract_wet |> fit_issf(case ~ sl + log_sl + cos_ta + 
                                            built_2020 + cropland_2020 + grassland_2020 + shrub_2020 + tree_2020 + 
                                            water_2020 + core_dist_rast + rivers_dist_rast + roads_distance_rast + 
                                            fences_dist_rast + log_pop_density_2020 + wet_szn_evi_2020 + 
                                            elevation + slope + aspect + strata(step_id),
                                          model = FALSE)
summary(m0_wet)

```

```{r}
#save model outputs
saveRDS(m0_wet, here("outputs/m0_wet.rds"))
saveRDS(m0_dry, here("outputs/m0_dry.rds"))
saveRDS(ele_trk_extract_wet, here("outputs/ele_trk_extract_wet.rds"))
saveRDS(ele_trk_extract_dry, here("outputs/ele_trk_extract_dry.rds"))
# save raster stacks
saveRDS(raster_stack_wet, here("outputs/raster_stack_wet.rds"))
saveRDS(raster_stack_dry, here("outputs/raster_stack_dry.rds"))
```



